"""empty message

Revision ID: 6bfb81d22b74
Revises: 3ffdea52697d
Create Date: 2025-09-23 03:37:47.880642

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bfb81d22b74'
down_revision = '3ffdea52697d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailbox', sa.Column('disable_smime', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('mailbox', sa.Column('smime_public_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mailbox', 'smime_public_key')
    op.drop_column('mailbox', 'disable_smime')
    # ### end Alembic commands ###
