"""empty message

Revision ID: 9f6b47cfc11b
Revises: 6bfb81d22b74
Create Date: 2025-09-23 05:26:02.761958

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f6b47cfc11b'
down_revision = '6bfb81d22b74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alias', sa.Column('disable_smime', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alias', 'disable_smime')
    # ### end Alembic commands ###
